Bl808 module mb doc
bouffalolab/blwnet_xram pull request #1
Opened 2023-08-25 01:48 UTC by fangzheli

2023-08-25 07:50 UTC, ivq commented on doc/BL808_Module_MB/BL808_Module_MB_how_to.MD
> +![Alt text](https://github.com/fangzheli/blwnet_xram/blob/BL808_Module_MB_doc/doc/burn.png?raw=true "Burning options")
All "fangzheli/blwnet" should be changed to "bouffalolab/blwnet_xram".

2023-08-25 07:52 UTC, ivq requested changes
Thank you for contributing. However links in the doc should be changed or we will need to rework.

2023-08-25 16:54 UTC, fangzheli commented on doc/BL808_Module_MB/BL808_Module_MB_how_to.MD
> +![Alt text](https://github.com/fangzheli/blwnet_xram/blob/BL808_Module_MB_doc/doc/burn.png?raw=true "Burning options")
Thanks, will change it to relative path, sorry for that.

2023-08-26 12:19 UTC, ivq approved these changes

2023-08-26 12:19 UTC, merged